### ISSUE TITLE
[RuOK: Forge : 1.19.2]: Crash on world creation

### ISSUE THREAD

**Issue by SiverDX** [MCTeamPotato/RuOK#1]
Too many mods to list

Joining a world that was already created seems to be fine
(even if it's the one that crashed the game when being created)

**Latest log**

``` log
[13Sep2023 17:07:46.270] [Render thread/ERROR] [net.minecraft.client.Minecraft/FATAL]: Reported exception thrown!
net.minecraft.ReportedException: Starting integrated server
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:529) ~[client-1.19.2-20220805.130853-srg.jar%23853!/:?]
	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:85) ~[client-1.19.2-20220805.130853-srg.jar%23853!/:?]
	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:185) ~[client-1.19.2-20220805.130853-srg.jar%23853!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:103) ~[client-1.19.2-20220805.130853-srg.jar%23853!/:?]
	at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:184) ~[client-1.19.2-20220805.130853-srg.jar%23853!/:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar%2384!/:build 7]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar%2396!/:build 7]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar%2384!/:build 7]
	at com.mojang.blaze3d.systems.RenderSystem.m_69495_(RenderSystem.java:204) ~[client-1.19.2-20220805.130853-srg.jar%23853!/:?]
	at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:337) ~[client-1.19.2-20220805.130853-srg.jar%23853!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1143) ~[client-1.19.2-20220805.130853-srg.jar%23853!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23853!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23853!/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23853!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.21.jar%23150!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%23137!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%23137!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%23137!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%23137!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%23137!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%23137!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%23137!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57) [ForgeWrapper-mmc2.jar:mmc2]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) [NewLaunch.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.server.ReloadableServerResources.m_206860_()" because "this.f_129740_.f_206585_" is null
	at net.minecraft.server.MinecraftServer.<init>(MinecraftServer.java:279) ~[client-1.19.2-20220805.130853-srg.jar%23853!/:?]
	at net.minecraft.client.server.IntegratedServer.<init>(IntegratedServer.java:48) ~[client-1.19.2-20220805.130853-srg.jar%23853!/:?]
	at net.minecraft.client.Minecraft.lambda$doWorldLoad$42(Minecraft.java:1996) ~[client-1.19.2-20220805.130853-srg.jar%23853!/:?]
	at net.minecraft.server.MinecraftServer.m_129872_(MinecraftServer.java:253) ~[client-1.19.2-20220805.130853-srg.jar%23853!/:?]
	at net.minecraft.client.Minecraft.m_231380_(Minecraft.java:1995) ~[client-1.19.2-20220805.130853-srg.jar%23853!/:?]
	at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.m_233107_(WorldOpenFlows.java:96) ~[client-1.19.2-20220805.130853-srg.jar%23853!/:?]
	at net.minecraft.client.gui.screens.worldselection.CreateWorldScreen.m_232867_(CreateWorldScreen.java:276) ~[client-1.19.2-20220805.130853-srg.jar%23853!/:?]
	at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.m_233126_(WorldOpenFlows.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23853!/:?]
	at net.minecraft.client.gui.screens.worldselection.CreateWorldScreen.m_100972_(CreateWorldScreen.java:265) ~[client-1.19.2-20220805.130853-srg.jar%23853!/:?]
	at net.minecraft.client.gui.screens.worldselection.CreateWorldScreen.m_232937_(CreateWorldScreen.java:215) ~[client-1.19.2-20220805.130853-srg.jar%23853!/:?]
	at net.minecraft.client.gui.components.Button.m_5691_(Button.java:43) ~[client-1.19.2-20220805.130853-srg.jar%23853!/:?]
	at net.minecraft.client.gui.components.AbstractButton.m_5716_(AbstractButton.java:16) ~[client-1.19.2-20220805.130853-srg.jar%23853!/:?]
	at net.minecraft.client.gui.components.AbstractWidget.m_6375_(AbstractWidget.java:110) ~[client-1.19.2-20220805.130853-srg.jar%23853!/:?]
	at net.minecraft.client.gui.components.events.ContainerEventHandler.m_6375_(ContainerEventHandler.java:27) ~[client-1.19.2-20220805.130853-srg.jar%23853!/:?]
	at net.minecraft.client.MouseHandler.m_168084_(MouseHandler.java:88) ~[client-1.19.2-20220805.130853-srg.jar%23853!/:?]
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:522) ~[client-1.19.2-20220805.130853-srg.jar%23853!/:?]
	... 34 more
```

**Crash log**

[crash.log](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/12599675/crash.log)

**Comment by Kasualix** [comment]
@AweiMC

**Comment by AweiMC** [comment]
RuOK version 1.3.0 should have fixed this crash issue
